__title__ = 'boltun'
__summary__ = 'Generate massive datasets from a single template file'
__uri__ = 'https://github.com/meiblorn/boltun'
__author__ = 'Vadim Fedorenko (Meiblorn)'
__email__ = 'meiblorn@gmail.com'
__license__ = 'MIT'
